// <auto-generated />
using System;
using BeleskeBlazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeleskeBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240407212811_AllTables2")]
    partial class AllTables2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Beleska", b =>
                {
                    b.Property<int>("IdBeleska")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBeleska"));

                    b.Property<byte[]>("dokument")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("idCas")
                        .HasColumnType("int");

                    b.Property<int>("idStudent")
                        .HasColumnType("int");

                    b.Property<string>("naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("redniBroj")
                        .HasColumnType("int");

                    b.HasKey("IdBeleska");

                    b.ToTable("Beleska");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Cas", b =>
                {
                    b.Property<int>("IdCas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCas"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdDrzi")
                        .HasColumnType("int");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCas");

                    b.ToTable("Cas");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.DrziUSemestru", b =>
                {
                    b.Property<int>("IdDrzi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDrzi"));

                    b.Property<int>("IdPredmet")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<int>("IdSemestar")
                        .HasColumnType("int");

                    b.HasKey("IdDrzi");

                    b.ToTable("DrziUSemestru");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Predmet", b =>
                {
                    b.Property<int>("IdPredmet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPredmet"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPredmet");

                    b.ToTable("Predmet");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.HasKey("IdProfesor");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Semestar", b =>
                {
                    b.Property<int>("IdSemestar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSemestar"));

                    b.Property<string>("Broj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSemestar");

                    b.ToTable("Semestar");
                });

            modelBuilder.Entity("BeleskeBlazor.Client.Data.Model.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudent");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
